New plugin: tangorin
RoxasShadow/gauss pull request #3
Opened 2016-10-07 21:25 UTC by alfateam123

This is a (possible) implementation for the `tangorin` plugin that is already present in Descartes but not in Gauss.

I didn't write lots of Rust until now, so if you spot something that is not idiomatic, or could be done better, or just mistakes I overlooked, I'll be more than happy to fix them.

Fixes #2

2016-10-08 22:20 UTC, RoxasShadow requested changes

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            Some(captures) => {
`Some(captures) => captures.at(1).map(|e| e.to_owned())`

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            let node    = match_.as_node().first_child().unwrap();
check the indentation here, it looks quite weird

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            let mut retrieved_text = borrowed_text.clone();
I think this doesn't need to be mutable as you should be able to do everything in a single line, right?

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +        else{
I don't like much this line. What about an early return on the very top of the function?

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            let mut meaning = "".to_string();
`String::new()` in place of `"".to_string()`

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            for child_ in children {
What about just `child`?

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                if let Some(text_) = child_.as_text() {
`text`?

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +        else{
As before, maybe an early return would work better

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            else{
I don't find value in this `else`

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            Some(res.clone())
prefer `to_owned()` in place of `clone()`. Btw I think this block can be make shorter

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            Some(kanji) => "http://tangorin.com/general/".to_string() + kanji.as_str(),
Let's use `format!` for this

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            let romaji = match self.retrieve_from_selector(&doc, "rt"){
What if we make a macro to reduce this redundant lines?

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                    (" (".to_string()+sanitized.as_str()+")").to_string()
`format!`

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                None => "".to_string()
`String::new`

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            return server.send_privmsg(target, &format!("[Tangorin] {} ({} - {}): {}{}", &*kanji, &*kana, &*romaji, &*meaning, &*info))
I'm pretty sure that filling a proper struct with these data and using the `ToString` trait would work great

2016-10-08 22:20 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +
useless line here, one is enough

2016-10-09 17:42 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +
should be fixed

2016-10-09 17:43 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +                None => "".to_string()
fixed.

2016-10-09 17:43 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +                    (" (".to_string()+sanitized.as_str()+")").to_string()
i felt there was a better way to do that, but didn't look at the docs. fixed.

2016-10-09 17:44 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            let romaji = match self.retrieve_from_selector(&doc, "rt"){
implemented a simple macro called `get_text!`. it definitely cuts the noise down.

2016-10-09 17:44 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            Some(kanji) => "http://tangorin.com/general/".to_string() + kanji.as_str(),
fixed

2016-10-09 17:46 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            Some(res.clone())
the code now uses `to_owned`.

2016-10-09 17:47 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            for child_ in children {
old habits are hard to kill. fixed now.

2016-10-09 17:47 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +                if let Some(text_) = child_.as_text() {
old habits, again.

2016-10-09 17:47 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            let mut meaning = "".to_string();
fixed

2016-10-09 17:47 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +        else{
refactored the whole thing, so early returns are not necessary anymore.

2016-10-09 17:49 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            let mut retrieved_text = borrowed_text.clone();
now this not mutable anymore. Originally, I had some problems with `borrowed_text` lifetimes: to fix it I put each change to its own line, but didn't recompose things back.

2016-10-09 17:50 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            let node    = match_.as_node().first_child().unwrap();
ssh on spotty connections is suffering and makes me miss this kind of errors. fixed.

2016-10-09 17:50 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            Some(captures) => {
done

2016-10-09 17:56 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            return server.send_privmsg(target, &format!("[Tangorin] {} ({} - {}): {}{}", &*kanji, &*kana, &*romaji, &*meaning, &*info))
I don't really think so. Creating an useless struct just to use `.to_string` is not as readable as a `format!`, especially considering that the retrieved information is not shared with other plugins or stored in any way.

2016-10-09 19:23 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            return server.send_privmsg(target, &format!("[Tangorin] {} ({} - {}): {}{}", &*kanji, &*kana, &*romaji, &*meaning, &*info))
At least let's try to format that string properly (splitting the vars in multiple lines just work fine) as right now that's. `struct` as very lightweight btw :)

2016-10-09 19:42 UTC, RoxasShadow requested changes

2016-10-09 19:42 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                Some(borrowed_text.clone().trim().to_string())
`to_owned()` is better than `clone()` as it is an its specialisation

2016-10-09 19:42 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +macro_rules! get_text {
`try_option` to be more similar to `try`?

2016-10-09 19:42 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            None => None,
Can you think a way to avoid this `None => None` in many places? like an early return or so

2016-10-09 19:42 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                    else{
put a space after `else` please

2016-10-09 19:42 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                    Err(()) => None,
`Err(_)`?

2016-10-09 19:42 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                    Ok(mut info_sibs) => {
you can avoid `{...}` as using direct `=> match` is enough

2016-10-09 19:42 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                        match info_sibs.next() {
`info_sibs.next().map(|n| ...)`

2016-10-09 19:42 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                match match_.as_text() {
`match_.as_text().map(|n| ...)`

2016-10-11 20:02 UTC, winterthediplomat commented on src/plugins/tangorin.rs
> +                    Ok(mut info_sibs) => {
good catch

2016-10-11 20:02 UTC, winterthediplomat commented on src/plugins/tangorin.rs
> +                    Err(()) => None,
fixed

2016-10-11 20:02 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +                    else{
fixed

2016-10-11 20:04 UTC, winterthediplomat commented on src/plugins/tangorin.rs
> +            None => None,
as discussed privately, I've switched to `Options.map` when the conversion is easy and meaningful.

2016-10-11 20:05 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +macro_rules! get_text {
done.

2016-10-11 20:05 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +                match match_.as_text() {
done

2016-10-11 20:05 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +                        match info_sibs.next() {
done

2016-10-12 08:47 UTC, RoxasShadow requested changes

2016-10-12 08:47 UTC, RoxasShadow commented on src/plugins/tangorin.rs
>                  let node = match_.as_node().first_child().unwrap();
there's an indentation problem here maybe?

2016-10-12 08:47 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                else {
elsif?

2016-10-12 08:47 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                let node = match_.as_node().first_child().unwrap();
indentation problem here

2016-10-12 08:47 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +        match root.first_child(){
put a space before the `{`

2016-10-12 08:47 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +            let info : String = match self.retrieve_info(&doc) {
don't put any space before the `:` (i.e. `let info: String =`)

2016-10-12 08:47 UTC, RoxasShadow commented on src/plugins/tangorin.rs
> +                Some(retrieved) => format!(" ({})", retrieved.replace("\u{2014}", "").replace(".", "").to_lowercase()),
WDYT about `String::remove` here?

2016-10-12 08:48 UTC, RoxasShadow commented
This is cool, just a couple of request changes and we can merge this – thanks a lot  👍

2016-10-12 20:03 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +                Some(retrieved) => format!(" ({})", retrieved.replace("\u{2014}", "").replace(".", "").to_lowercase()),
unfortunately [String::remove](https://doc.rust-lang.org/std/string/struct.String.html#method.remove) does not do what we thought it does: 
`Removes a char from this String at a byte position and returns it.`.
String::replace is still the way to go.

2016-10-12 20:04 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +            let info : String = match self.retrieve_info(&doc) {
ops :///:

2016-10-12 20:05 UTC, alfateam123 commented on src/plugins/tangorin.rs
>                  let node = match_.as_node().first_child().unwrap();
fixed

2016-10-12 20:05 UTC, winterthediplomat commented on src/plugins/tangorin.rs
> +                let node = match_.as_node().first_child().unwrap();
forgot to fix it in the previous patch :V

2016-10-12 20:05 UTC, alfateam123 commented on src/plugins/tangorin.rs
> +        match root.first_child(){
fixed

2016-10-12 20:06 UTC, winterthediplomat commented on src/plugins/tangorin.rs
> +                else {
fixed

2016-10-12 20:34 UTC, merged